package uninstall

import (
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"strings"
)

// GitHookItem represents a git hook that can be removed
type GitHookItem struct {
	Path        string // full path to hook file
	Name        string // hook name (e.g., "pre-commit")
	HasMixed    bool   // true if hook contains both SageOx and non-SageOx content
	IsEntireSox bool   // true if entire file is SageOx content
}

// sageoxHookMarkers are patterns that identify SageOx-installed hooks
// These should appear in comments at the top of hook files
var sageoxHookMarkers = []string{
	"# ox pre-commit hook",
	"# ox post-commit hook",
	"# ox prepare-commit-msg hook",
	"# ox commit-msg hook",
	"# SageOx hook",
	"# Generated by ox",
}

// beadsHookMarker identifies beads sync sections in hooks.
// legacy cleanup: users may have beads hooks from prior ox versions
const beadsHookMarker = "# bd-hooks-version:"

// FindSageoxHooks scans .git/hooks/ directory for SageOx-installed hooks
// Returns list of hooks that contain SageOx markers
func FindSageoxHooks(repoRoot string) ([]GitHookItem, error) {
	hooksDir := filepath.Join(repoRoot, ".git", "hooks")

	// check if hooks directory exists
	if _, err := os.Stat(hooksDir); os.IsNotExist(err) {
		return nil, nil
	}

	entries, err := os.ReadDir(hooksDir)
	if err != nil {
		return nil, fmt.Errorf("reading hooks directory: %w", err)
	}

	var items []GitHookItem

	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}

		name := entry.Name()
		// skip .sample files - these are git-provided examples
		if strings.HasSuffix(name, ".sample") {
			continue
		}

		hookPath := filepath.Join(hooksDir, name)

		// analyze hook file
		hasSageox, hasMixed, isEntireSox, err := analyzeHookFile(hookPath)
		if err != nil {
			slog.Debug("failed to analyze hook file", "path", hookPath, "error", err)
			continue
		}

		if hasSageox {
			items = append(items, GitHookItem{
				Path:        hookPath,
				Name:        name,
				HasMixed:    hasMixed,
				IsEntireSox: isEntireSox,
			})
		}
	}

	return items, nil
}

// analyzeHookFile examines a hook file to determine SageOx content
// Returns: (hasSageox, hasMixed, isEntireSox, error)
// - hasSageox: true if file contains any SageOx markers
// - hasMixed: true if file contains both SageOx and non-SageOx content
// - isEntireSox: true if entire file is SageOx content (can be deleted)
func analyzeHookFile(path string) (bool, bool, bool, error) {
	content, err := os.ReadFile(path)
	if err != nil {
		return false, false, false, err
	}

	contentStr := string(content)

	// check for SageOx markers
	hasSageox := false
	for _, marker := range sageoxHookMarkers {
		if strings.Contains(contentStr, marker) {
			hasSageox = true
			break
		}
	}

	// also check for beads hook marker
	if strings.Contains(contentStr, beadsHookMarker) {
		hasSageox = true
	}

	if !hasSageox {
		return false, false, false, nil
	}

	// determine if hook is entirely SageOx or mixed
	// A hook is considered entirely SageOx if:
	// 1. It starts with a shebang and SageOx marker
	// 2. All non-comment, non-empty lines are within SageOx sections
	// 3. No other tool markers are present (e.g., no "# husky", "# lefthook", etc.)

	lines := strings.Split(contentStr, "\n")
	hasNonSageoxContent := false
	inSageoxSection := false

	for i, line := range lines {
		trimmed := strings.TrimSpace(line)

		// skip empty lines
		if trimmed == "" {
			continue
		}

		// skip shebang
		if i == 0 && strings.HasPrefix(trimmed, "#!") {
			continue
		}

		// check for SageOx section markers
		if containsAny(trimmed, sageoxHookMarkers) || strings.Contains(trimmed, beadsHookMarker) {
			inSageoxSection = true
			continue
		}

		// check for other tool markers (indicates mixed content)
		otherToolMarkers := []string{
			"# husky",
			"# lefthook",
			"# pre-commit.com",
			"# lint-staged",
		}
		if containsAny(trimmed, otherToolMarkers) {
			hasNonSageoxContent = true
			break
		}

		// if it's a comment within SageOx section, it's SageOx content
		if strings.HasPrefix(trimmed, "#") && inSageoxSection {
			continue
		}

		// if it's code but we haven't seen a SageOx marker yet, it's non-SageOx
		if !inSageoxSection && !strings.HasPrefix(trimmed, "#") {
			hasNonSageoxContent = true
		}
	}

	isEntireSox := !hasNonSageoxContent
	hasMixed := !isEntireSox

	return true, hasMixed, isEntireSox, nil
}

// containsAny returns true if s contains any of the patterns
func containsAny(s string, patterns []string) bool {
	for _, pattern := range patterns {
		if strings.Contains(s, pattern) {
			return true
		}
	}
	return false
}

// RemoveRepoHooks removes SageOx hooks from .git/hooks/
// If dryRun is true, only reports what would be removed without making changes
// Returns error if any removal fails
func RemoveRepoHooks(repoRoot string, dryRun bool) error {
	items, err := FindSageoxHooks(repoRoot)
	if err != nil {
		return fmt.Errorf("finding SageOx hooks: %w", err)
	}

	if len(items) == 0 {
		slog.Info("no SageOx hooks found in repository")
		return nil
	}

	for _, item := range items {
		if item.IsEntireSox {
			// entire file is SageOx - delete it
			if dryRun {
				slog.Info("would remove hook file (entire file is SageOx)", "hook", item.Name, "path", item.Path)
			} else {
				if err := os.Remove(item.Path); err != nil {
					return fmt.Errorf("removing hook %s: %w", item.Name, err)
				}
				slog.Info("removed hook file", "hook", item.Name)
			}
		} else if item.HasMixed {
			// mixed content - remove only SageOx portions
			if dryRun {
				slog.Info("would remove SageOx sections from hook (mixed content)", "hook", item.Name, "path", item.Path)
			} else {
				if err := removeSageoxSections(item.Path); err != nil {
					return fmt.Errorf("removing SageOx sections from %s: %w", item.Name, err)
				}
				slog.Info("removed SageOx sections from hook", "hook", item.Name)
			}
		}
	}

	return nil
}

// removeSageoxSections removes SageOx-specific sections from a hook file
// Preserves non-SageOx content and other tool integrations
func removeSageoxSections(path string) error {
	content, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("reading hook file: %w", err)
	}

	lines := strings.Split(string(content), "\n")
	var cleanedLines []string
	inSageoxSection := false
	consecutiveBlankLines := 0

	for i, line := range lines {
		trimmed := strings.TrimSpace(line)

		// preserve shebang
		if i == 0 && strings.HasPrefix(trimmed, "#!") {
			cleanedLines = append(cleanedLines, line)
			continue
		}

		// detect SageOx section start
		if containsAny(line, sageoxHookMarkers) || strings.Contains(line, beadsHookMarker) {
			inSageoxSection = true
			continue // skip the marker line
		}

		// if we're in a SageOx section
		if inSageoxSection {
			// check for other tool markers (these end the SageOx section)
			otherToolMarkers := []string{
				"# husky",
				"# lefthook",
				"# pre-commit.com",
				"# lint-staged",
			}
			if containsAny(trimmed, otherToolMarkers) {
				inSageoxSection = false
				consecutiveBlankLines = 0
				cleanedLines = append(cleanedLines, line)
				continue
			}

			// track blank lines - 2+ consecutive blank lines likely indicate section end
			if trimmed == "" {
				consecutiveBlankLines++
				// if we've seen 2+ blank lines, the section probably ended
				if consecutiveBlankLines >= 2 {
					inSageoxSection = false
					// add the blank line to preserve spacing
					cleanedLines = append(cleanedLines, line)
				}
				continue
			}

			// if it's a comment starting with # but not a SageOx marker
			// and we've seen at least one blank line, it's probably a new section
			if strings.HasPrefix(trimmed, "#") && consecutiveBlankLines > 0 {
				// this is likely a new section - end SageOx section
				inSageoxSection = false
				consecutiveBlankLines = 0
				cleanedLines = append(cleanedLines, line)
				continue
			}

			// still in SageOx section - skip this line
			consecutiveBlankLines = 0
			continue
		}

		// not in SageOx section - preserve line
		consecutiveBlankLines = 0
		cleanedLines = append(cleanedLines, line)
	}

	// write cleaned content back
	cleaned := strings.Join(cleanedLines, "\n")

	// preserve original file permissions
	info, err := os.Stat(path)
	if err != nil {
		return fmt.Errorf("getting file info: %w", err)
	}

	if err := os.WriteFile(path, []byte(cleaned), info.Mode()); err != nil {
		return fmt.Errorf("writing cleaned hook file: %w", err)
	}

	return nil
}
